FROM node:22.23.2-alpine3.24

RUN apk add --no-cache python3 py3-virtualenv rust cargo patch postgresql-client \
    && virtualenv /opt/venv \
    && /opt/venv/bin/pip install --no-cache-dir pytest==9.1.1 \
    && npm install --global --no-audit --no-fund typescript@5.7.3

ENV PATH="/opt/venv/bin:${PATH}"
ENTRYPOINT []
